# NUMPY

In [5]:
## import numpy
import numpy as np

In [6]:
my_list=[1,2,3,4,5]

In [7]:
type(my_list)

list

In [8]:
arr=np.array(my_list)

In [9]:
type(arr)

numpy.ndarray

In [10]:
print(arr)

[1 2 3 4 5]


In [11]:
arr.shape

(5,)

In [12]:
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]

In [13]:
arr=np.array([my_list1,my_list2,my_list3])

In [14]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
arr.shape

(3, 5)

In [18]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [19]:
arr.shape

(3, 5)

# Indexing

In [20]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [21]:
arr[3]

4

In [22]:
 arr=np.array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])


In [23]:
arr[:,:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [24]:
arr[1:,3:]

array([], shape=(4, 0), dtype=int32)

In [25]:
arr[1:1:]

array([], shape=(0, 3), dtype=int32)

In [26]:
arr[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr[0:2,0:1]

array([[1],
       [4]])

In [29]:
arr=np.arange(0,10)

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr=np.arange(0,10,3)

In [32]:
arr

array([0, 3, 6, 9])

In [33]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [34]:
## copy function
arr

array([0, 3, 6, 9])

In [40]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr[3:]=100

In [39]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [41]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr1=arr

In [43]:
arr1[5:]=500

In [44]:
arr1

array([  0,   1,   2,   3,   4, 500, 500, 500, 500, 500])

In [45]:
arr

array([  0,   1,   2,   3,   4, 500, 500, 500, 500, 500])

In [46]:
arr=np.arange(0,10)

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr1=arr.copy()

In [49]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr1[5:]=100

In [52]:
arr1

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [53]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [55]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [56]:
np.ones(4)

array([1., 1., 1., 1.])

In [60]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
## random distribution

In [62]:
np.random.rand(3,3)

array([[0.89446723, 0.43686722, 0.48337838],
       [0.36176167, 0.88029131, 0.22322639],
       [0.64074573, 0.35938092, 0.27040685]])

In [63]:
arr_ex = np.random.randn(4,4)

In [66]:

arr_ex

array([[-0.67824643, -0.19362837, -0.58251821,  0.28716983],
       [-1.66431546,  1.45854995, -0.06274676,  1.58205041],
       [ 0.65183212, -0.16638995, -1.59882293,  0.80564729],
       [ 1.08599369, -0.78847388,  1.98260281,  0.61997495]])

In [67]:
np.random.randint(0,100,10)

array([42, 16, 83, 57, 90, 54, 99, 88,  2, 59])

In [70]:
np.random.random_sample((5,5))

array([[0.60023906, 0.82537424, 0.70826431, 0.41944071, 0.36797598],
       [0.63646304, 0.78795942, 0.13634413, 0.43321928, 0.5931466 ],
       [0.39267392, 0.54957732, 0.24533667, 0.39709091, 0.07634682],
       [0.2884184 , 0.09939414, 0.40818905, 0.23299854, 0.49647084],
       [0.72061122, 0.23621749, 0.6658754 , 0.44226317, 0.82424762]])